FROM        node:14-buster-slim

LABEL       author="Samuel Voeller" maintainer="samuel.voeller@mxsrv.amethyst.live"

RUN         apt update \
            && apt -y install build-essential ca-certificates dnsutils ffmpeg g++ gcc git iproute2 libsqlite3-dev make python3 python3-dev sqlite3 tzdata zip \
            && npm install -g node-gyp nodemon \
            && useradd -m -d /home/container container

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./entrypoint.sh /entrypoint.sh
CMD         ["/bin/bash", "/entrypoint.sh"]
