FROM        ghcr.io/amethyst-studio/yolks:node_14

LABEL       author="Samuel Voeller" maintainer="samuel.voeller@mxsrv.amethyst.live"

COPY ./installer.sh ./installer.sh
ENTRYPOINT ["./installer.sh"]
