FROM node:14-buster-slim

LABEL author="Samuel J Voeller" maintainer="samuel.voeller@amethyst.live"

LABEL org.opencontainers.image.source="https://github.com/amethyst-studio/pterodactyl-nest.git"
LABEL org.opencontainers.image.description="Runnable Node.js container for Pterodactyl. This image is intended to be used for application hosting."
LABEL org.opencontainers.image.licenses=MIT

RUN \
  dpkg --add-architecture i386 && \
  apt-get update && apt-get upgrade -y && \
  apt install --no-install-recommends -y build-essential ca-certificates dnsutils ffmpeg g++ gcc git iproute2 libsqlite3-dev make python3 python3-dev sqlite3 tzdata zip
RUN apt-get autoremove -y && apt-get clean autoclean && rm -rf /var/lib/apt/lists/*

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh
CMD ["/bin/bash", "/entrypoint.sh"]
