name: 'Node.js'

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - .github/workflows/node.yml
      - yolk/node/*

jobs:
  push:
    name: 'yolks:node_${{ matrix.tag }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - 16
          - 15
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./yolk/node/
          file: ./node/Dockerfile_${{ matrix.tag }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/xcykrix/yolks:node_${{ matrix.tag }}